### ISSUE TITLE
Deployments

### ISSUE THREAD

**Issue by keirdavie** [keirdavie/saascape#9]
# Brief

Deployments allow us to group instances together for the purpose of controlling releases to those instances. So once a deployment has been created and assigned to an instance, we can then deploy a version to that deployment group. Resulting in all of the specified instances to be updated to the same version.

### Tasks
- [x] Ensure correct deployment status is being set on finish
- [x] Check whether current job is last in queue, if so then wrap up the deployment
- [x] Implement socket updates to ensure the FE is kept up to date
